version: "3.3"

services:
  docker_mysql:
    container_name: docker_mysql
    image: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./db-bin/mysql:/var/lib/mysql
    env_file:
      - ./envs/mysql.env

  docker_postgres:
    container_name: docker_postgres
    image: postgres:13.2-alpine
    restart: always
    ports:
      - 54321:5432
    volumes:
      - ./db-bin/postgres:/var/lib/postgresql/data
    env_file:
      - ./envs/postgres.env

  docker_redis:
    container_name: docker_redis
    image: redis:6.2.1-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./db-bin/redis:/data
