version: "3.3"

services:
  docker_mysql:
    container_name: docker_mysql
    image: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - bin-mysql:/var/lib/mysql
    env_file:
      - ./envs/mysql.env
    networks:
      - database-network

  docker_postgres:
    container_name: docker_postgres
    image: postgres:13.2-alpine
    restart: always
    ports:
      - 54321:5432
    volumes:
      - bin-postgres:/var/lib/postgresql/data
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    networks:
      - database-network

  docker_redis:
    container_name: docker_redis
    image: redis:6.2.1-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - bin-redis:/data
    networks:
      - database-network
######### Volumes & Network ###################################
networks:
  database-network:
    name: docker-database-network
    driver: bridge
volumes:
  bin-mysql:
  bin-postgres:
  bin-redis:
    driver: local
